# Predict an applicant's outcome when they apply to CSH using past data. Employs logistic regression to identify potential outcome classes. Check out the README for a better explanation.  
        
# By : Dylan P. Jackson
check out [my website](https://dylanpjackson.com) please <3 and maybe hire me if you want

In [15]:
# Them imports yo (Will probably need more)
import numpy as np
from "../../../repos/ai_implementations/custom_ai_utils" import sigmoid

SyntaxError: invalid syntax (<ipython-input-15-66df24087edb>, line 3)

In [10]:
# Load in some data
data_path = "data/intro.csv"
data = np.loadtxt(data_path, delimiter = ",", usecols = (1,2,3,4,5,6))

[[ 25.   0.  25.   5.   1.   2.]
 [ 30.   0.  19.   7.   1.   0.]
 [ 22.   0.  15.   2.   1.   1.]
 ..., 
 [  0.   0.  27.   5.   1.   1.]
 [  8.   0.  22.   2.   1.   1.]
 [ 20.   1.   5.   2.   0.   2.]]


In [ ]:
# Sigmoid function

# Compute sigmoid on z, whether it be a scalar, vector, or matrix
def sigmoid(z):
    